# Generated by Django 3.0.3 on 2020-07-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finaldemo', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
